server:
  port: 8988
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/landrzejewski/spring-cloud
          search-paths: clinic-config-repo